name: ProjectJules
options:
  bundleIdPrefix: com.projectjules
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

targets:
  ProjectJules:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: App
      - path: DesignSystem
      - path: Models
      - path: Services
      - path: Views
      - path: Config
    resources:
      - path: Assets
        type: folder
        createIntermediateGroups: true
    info:
      path: Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UILaunchScreen: {}
        UIAppFonts:
          - PlayfairDisplay-Regular.ttf
          - PlayfairDisplay-SemiBold.ttf
          - Inter-Regular.ttf
          - Inter-Medium.ttf
          - Inter-SemiBold.ttf
        NSPhotoLibraryUsageDescription: "Jules needs access to your photos to set up your profile."
        NSCameraUsageDescription: "Jules needs access to your camera to take profile photos."
        NSLocationWhenInUseUsageDescription: "Jules uses your location to find matches and suggest nearby venues."
        NSMicrophoneUsageDescription: "Jules needs access to your microphone to record voice notes."
    dependencies:
      - package: supabase-swift
        product: Supabase
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.projectjules.ProjectJules
        PRODUCT_NAME: ProjectJules
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
packages:
  supabase-swift:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"

